filebeat.inputs:
- type: filestream
  id: my-filestream-id
  enabled: false
  paths:
    - /var/log/*.log
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true
setup.template.settings:
  index.number_of_shards: 1
setup.kibana:
  host: "192.168.31.11:5601"
output.elasticsearch:
  hosts: ["192.168.31.11:9200"]
  preset: balanced
  protocol: "https"
  username: "elastic"
  password: "X73CU9r9YWaP==bM0agj"
 
  ssl.certificate_authorities: "/etc/elasticsearch/certs/http_ca.crt"
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
